name: business
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  domain:
    path: packages/domain
  data:
    path: packages/data
  usecase:
    path: packages/usecase
  injectable: any
  get_it: any

dev_dependencies:
  test: any
  flutter_lints: any
  injectable_generator: any
  build_runner: any