import 'dart:math';

class MockNames {
  static const names = [
    'João Albuquerque',
    'Rute Batista',
    'Soraia Braz',
    'Luís Rita',
    'Luísa Ramos',
    'Gil Fonseca',
    'Leonor Lemos',
    'Isaú Vale',
    'Ilda Mascarenhas',
    'Tomás Carmo',
    'Álvaro Palma',
    'Magda Faustino',
    'Virgílio Marinho',
    'Carla Fidalgo',
    'Rafael Fragoso',
    'Agostinho Veiga',
    'Margarida Leitão',
    'Fatima Barreto',
    'Manuela Dantas',
    'Rafaela Veríssimo',
    'Ernesto Gama',
    'Débora Freitas',
    'Lucinda Quaresma',
    'Artur Moniz',
    'Eduardo Soares',
    'Ivone Araújo',
    'Cristiana Marques',
    'Renato Baltazar',
    'Eugênio Miranda',
    'Elisabete Domingos',
    'Ze Guerreiro',
    'Arlindo Campos',
    'Jéssica Vasconcelos',
    'Fátima Frade',
    'Claúdia Noronha',
    'Julião Baptista',
    'Marcos Fernandes',
    'Madalena Pimentel',
    'Ruben Moita',
    'Nelson Resende',
    'Cristiana Péres',
    'Juliana Vicente',
    'Alfredo Abrantes',
    'Abel Couto',
    'António Furtado',
    'Aurora Lopes',
    'Márcio da Costa',
    'Adélia Seabra',
    'Ema Mendes',
    'Érita Neves',
    'Devon Day',
    'Júlia Paradis',
    'Garry Duncan',
    'Amanda Boucher',
    'Mona Lemieux',
    'Joseph Langevin',
    'Charlotte Larouche',
    'Dana Burns',
    'Jaime Rousseau',
    'Julien Grant',
    'Yvette Sutherland',
    'Brittany Brisebois',
    'Walter Gendron',
    'Ken Rodgers',
    'Hui Gill',
    'Irene Sanderson',
    'Austin Singh',
    'Kai Toews',
    'Stephen McDougall',
    'Jake Auger',
    'Beverley Tardif',
    'Kimberley Trottier',
    'Brett Wagner',
    'Garth Brown',
    'Stuart Roussel',
    'Bernice Larochelle',
    'Al Barker',
    'Lewis Pilon',
    'Therese Lavigne',
    'Yolande Ladouceur',
    'Yvan MacNeil',
    'Jéssica Maltais',
    'Bert Beauregard',
    'Agnes Ng',
    'Yu Mann',
    'Juanita Chang',
    'Sherri Carrier',
    'Andrzej Lepage',
    'Jasmine Fung',
    'Marcel Cardinal',
    'Frederick Owen',
    'Geo Jenkins',
    'Scott Guillemette',
    'Kimberly Leonard',
    'Marjorie Proulx',
    'Ivy Cheung',
    'Albert Foster',
    'Yannick Anderson',
    'Adrian Gillis',
    'Lori Hughes',
    'Carrol Sosa',
    'Gabrielle Simpson',
    'Lilian White',
    'Ted Rodgers',
    'Brittany Swanson',
    'Mari Pearson',
    'Gerardo Pitts',
    'Cornell Bautista',
    'Belinda Pham',
    'Jimmie Patrick',
    'Kraig Kirby',
    'Luigi Avila',
    'Faustino Acosta',
    'Wilburn Esparza',
    'Elias Gaines',
    'Harrison Frederick',
    'Collin Cochran',
    'Blake Archer',
    'Markus Bolton',
    'Myles Cordova',
    'Lou Fernandez',
    'Norbert Knox',
    'Rachel Velazquez',
    'Mohamed Coleman',
    'Justin Stevenson',
    'Cleo Sanford',
    'Freida Ayers',
    'Amado Hernandez',
    'Russell Wilson',
    'Sam Waller',
    'Rusty Landry',
    'Matthew Hodges',
    'Katie Ortiz',
    'Lea Clayton',
    'Fannie Rowe',
    'Elaine Phelps',
    'Broderick Blanchard',
    'Suzette Long',
    'Allen Avery',
    'Lisa Greer',
    'Brandon Velez',
    'Gil Anderson',
    'Veronica Lawrence',
    'Nadia Christian',
    'Nona Green',
    'Stephan Campos',
    'Isidro Chaney',
    'Branden Rice',
    'Janis Raymond',
    'Tyron Schmitt',
    'Israel Cochran',
    'Vanessa Petty',
    'Cruz Warren',
    'Sarah Harris',
    'Chrystal Zavala',
    'Liz Jarvis',
    'Noreen Mcdonald',
    'Eugenio Garrison',
    'Hester Wolfe',
    'Jamal Yang',
    'Margarito Terry',
    'Rex Johns',
    'Bart Everett',
    'Nestor Mckay',
    'Monica Barton',
    'Fritz Mcknight',
    'Simone Travis',
    'Della Hicks',
    'Millie Sampson',
    'Carol Gonzalez',
    'Danny Tanner',
    'Cindy Peterson',
    'Rob Benjamin',
    'Arnulfo Watkins',
    'Norbert Blevins',
    'Nellie Moyer',
    'Ester Zuniga',
    'Malinda Pham',
    'Bryon Bray',
    'Amanda Wallace',
    'Jordon Kemp',
    'Lauren Turner',
    'Manual Liu',
    'Les Lucero',
    'Oren Bailey',
    'Marisa Davidson',
    'Damien Cole',
    'Tyrell Green',
    'Tod Parker',
    'Sterling Bullock',
    'Jackie Odonnell',
    'Elmer Adkins',
    'Roosevelt Fritz',
    'Freda Manning',
    'Bertha Dickson',
    'Inez Hunter',
    'Ruben Newton',
    'Lynne White',
    'Odessa Shelton',
    'Glenn Charles',
    'Lela Lynch',
    'Roslyn Booker',
    'Edison Andrade',
    'Selma Hayes',
    'Janis Swanson',
    'Delmar Chan',
    'Winston Young',
    'Carter Morse',
    'Madelyn Warner',
    'Wendi Reynolds',
    'Joan Brown',
    'Damon Orr',
    'Valentin Braun',
    'German Wiley',
    'Delbert Calderon',
    'Jayne Stuart',
    'Beverley Case',
    'Rachael Bass',
    'Eldon Blevins',
    'Curtis Mullins',
    'Janelle Oneal',
    'Leah Alvarez',
    'Numbers Houston',
    'Cesar Huff',
    'Janet King',
    'Derick Cowan',
    'Riley Anderson'
  ];

  static const emailProviders = [
    'gmail.com',
    'yandex.ru',
    'microsoft.com',
    'uol.com.br',
    'sapo.pt',
    'mail.ru',
    'globo.com',
    'facebook.com',
  ];

  static const gender = [
    'male',
    'female',
    'other'
  ];

  static const status = [
    'active',
    'inactive'
  ];

  static String getEmail(String name) {
    final joinChars = ['.', '-', '_'];
    final prefix = name.replaceAll(' ', getRandomElement<String>(joinChars));
    final provider = getRandomElement<String>(emailProviders);
    return '$prefix@$provider';
  }

  static String getRandomGender() => getRandomElement<String>(gender);

  static String getRandomStatus() => getRandomElement<String>(status);

  static T getRandomElement<T>(List<T> elements) {
    return elements[Random().nextInt(elements.length)];
  }
}